version: '3.8'
services:

  keycloak-container:
    image: quay.io/keycloak/keycloak:19.0.3
    expose:
      - 8080
    volumes:
      - keycloak-volume:/opt/keycloak/data
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: 
      - start-dev
      - --proxy=edge
      - --hostname-strict=false
      - --hostname-strict-https=false

  nginx-container:
    image: petschenek/nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - $PWD/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - keycloak-container

volumes:
  keycloak-volume:
    driver: local

networks:
  default:
    name: keycloak-network
    external: true